import FontProvider from "@/components/FontProvider/FontProvider";
import SettingsProvider from "@/context/SettingsContext";
import { ColorTheme, FontTheme } from "@/types";
import type { Metadata } from "next";
import { cookies } from "next/headers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieFont = cookieStore.get("font-theme")?.value as
    | FontTheme
    | undefined;
  const cookieColor = cookieStore.get("color-theme")?.value as
    | ColorTheme
    | undefined;
  return (
    <html lang="en" suppressHydrationWarning>
      <SettingsProvider color={cookieColor} font={cookieFont}>
        <FontProvider>
          <body data-font-theme={cookieFont} data-color-theme={cookieColor}>
            {children}
          </body>
        </FontProvider>
      </SettingsProvider>
    </html>
  );
}
